### ISSUE TITLE
Uncaught Error: Cannot call canGoBack because the webContents is unavailable. The WebView must be...

### ISSUE THREAD

**Issue by fintzen** [sean-codes/atom-browser#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-browser](https://github.com/sean-codes/atom-browser) package 0.51.0

### Stack Trace

Uncaught Error: Cannot call canGoBack because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/web-view.js:390

Error: Cannot call canGoBack because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at HTMLElement.canGoBack (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/web-view.js:390:15)
    at Object.back (/packages/atom-browser/lib/atom-browser.js:108:33)
    at /packages/atom-browser/lib/atom-browser.js:66:68)
```

### Commands

```
     -3:00.1.0 editor:newline (input.hidden-input)
     -1:12.8.0 core:save (input.hidden-input)
     -1:09.7.0 core:backspace (input.hidden-input)
     -1:09.1.0 snippets:next-tab-stop (input.hidden-input)
     -1:09.1.0 snippets:expand (input.hidden-input)
     -1:09.1.0 editor:indent (input.hidden-input)
     -1:07.7.0 core:backspace (input.hidden-input)
     -1:07.0 snippets:next-tab-stop (input.hidden-input)
     -1:07.0 snippets:expand (input.hidden-input)
     -1:07.0 editor:indent (input.hidden-input)
  7x -1:04.1.0 core:backspace (input.hidden-input)
     -0:51.2.0 autocomplete-plus:confirm (input.hidden-input)
     -0:51.2.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  3x -0:50.6.0 core:backspace (input.hidden-input)
     -0:42.1.0 core:save (input.hidden-input)
     -0:24.6.0 atom-browser:showHide (input.hidden-input)
```

### Non-Core Packages

```
atom-browser 0.51.0 
```

**Comment by sean-codes** [comment]
Fixed up! :]
