### ISSUE TITLE
an error at the start

### ISSUE THREAD

**Issue by vBuresh** [sean-codes/atom-browser#48]
Hi!

At the start Atom Browser (an initial URL to start e.g. https://atom.io) an error like this occurs: 

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: Debian GNU/Linux 11
**Thrown From**: [atom-browser](ssh://git@github.com/sean-codes/atom-browser) package 1.10.0

### Stack Trace

Uncaught TypeError: this.html.webview.getWebContents is not a function

```
At /home/w/.atom/packages/atom-browser/lib/atom-browser-view-browser.js:223

TypeError: this.html.webview.getWebContents is not a function
    at AtomBrowserViewBrowser.reload (/packages/atom-browser/lib/atom-browser-view-browser.js:223:47)
    at /packages/atom-browser/lib/atom-browser-view-browser.js:155:18
```

### Commands

```
     -6:53.9.0 core:paste (input.hidden-input)
  2x -6:51.9.0 editor:newline (input.hidden-input)
     -6:35.2.0 intentions:highlight (input.hidden-input)
     -6:34 core:paste (input.hidden-input)
     -6:26.1.0 intentions:highlight (input.hidden-input)
     -6:24.5.0 tree-view:reveal-active-file (input.hidden-input)
     -5:59.5.0 editor:move-to-end-of-screen-line (input.hidden-input)
  2x -5:57.7.0 editor:newline (input.hidden-input)
     -5:56.1.0 intentions:highlight (input.hidden-input)
  2x -5:55 editor:newline (input.hidden-input)
  2x -5:54.2.0 core:move-up (input.hidden-input)
     -5:53.6.0 intentions:highlight (input.hidden-input)
     -5:52.5.0 core:paste (input.hidden-input)
     -4:43.2.0 intentions:highlight (input.hidden-input)
     -4:42.6.0 core:paste (input.hidden-input)
     -2:46.7.0 core:save-as (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4
atom-browser 1.10.0
atom-clock 0.1.18
atom-html-preview 0.2.6
atom-hugo 0.1.2
atom-translator 0.3.0
browser-plus 0.0.98
busy-signal 2.0.1
double-tag 1.7.0
emmet 2.4.3
font-viewer 1.0.5
hey-pane 1.2.0
intentions 1.1.5
language-hugo 0.5.1
language-markdown 0.37.0
language-svg 0.9.2
linter 3.3.1
linter-htmlhint 1.6.3
linter-sass-lint 1.9.0
linter-ui-default 3.3.1
minimap 4.39.13
minimap-cursorline 1.0.3
minimap-selection 4.5.4
pdf-view-plus 1.11.0
pigments 0.40.6
pinned-tabs 2.3.1
split-diff 1.6.1
svg-preview 0.14.0
svgo 5.0.0
termination 0.7.6
```
Thanks!

**Comment by Totogro** [comment]
Same problem here

[Enter steps to reproduce:]

1. right-clic on an html file and choose "Atom Browser: Preview"
(this error appears every time, even for files where it didn't appear before)

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: Ubuntu 20.04.2
**Thrown From**: [atom-browser](ssh://git@github.com/sean-codes/atom-browser) package 1.10.0


### Stack Trace

Uncaught TypeError: this.html.webview.getWebContents is not a function

```
At /home/redactedusername/.atom/packages/atom-browser/lib/atom-browser-view-browser.js:223

TypeError: this.html.webview.getWebContents is not a function
    at AtomBrowserViewBrowser.reload (/packages/atom-browser/lib/atom-browser-view-browser.js:223:47)
    at /packages/atom-browser/lib/atom-browser-view-browser.js:132:65)
```

### Commands

```
     -0:52.3.0 core:paste (input.hidden-input)
 14x -0:51.1.0 core:select-up (input.hidden-input)
     -0:49.4.0 editor:select-to-first-character-of-line (input.hidden-input)
     -0:48.8.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
     -0:48.8.0 snippets:next-tab-stop (input.hidden-input)
 15x -0:46.9.0 core:select-up (input.hidden-input)
     -0:45.5.0 core:select-down (input.hidden-input)
     -0:45.3.0 editor:select-to-first-character-of-line (input.hidden-input)
     -0:44.2.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
     -0:44.2.0 snippets:next-tab-stop (input.hidden-input)
     -0:44.2.0 snippets:expand (input.hidden-input)
     -0:44.2.0 editor:indent (input.hidden-input)
  2x -0:43.4.0 core:move-down (input.hidden-input)
     -0:37.8.0 intentions:highlight (input.hidden-input)
     -0:37.2.0 core:save (input.hidden-input)
     -0:34.7.0 atom-browser:preview (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
atom-browser 1.10.0 
atom-runner 2.7.1 
busy-signal 2.0.1 
emmet 2.4.3 
intentions 1.1.5 
linter 3.3.1 
linter-eslint 8.6.5 
linter-ui-default 3.3.1 
minimap 4.39.10 
pane-browser undefined 
```

**Comment by Lychfindel** [comment]
I am having the same issue, did you find a solution?

**Comment by vBuresh** [comment]
Hi!
Today I'm having: 

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Debian GNU/Linux
**Thrown From**: [atom-browser](ssh://git@github.com/sean-codes/atom-browser) package 1.10.0


### Stack Trace

Uncaught TypeError: this.html.webview.getWebContents is not a function

```
At /home/w/.atom/packages/atom-browser/lib/atom-browser-view-browser.js:283

TypeError: this.html.webview.getWebContents is not a function
    at AtomBrowserViewBrowser.zoomUpdate (/packages/atom-browser/lib/atom-browser-view-browser.js:283:29)
    at /packages/atom-browser/lib/atom-browser-view-browser.js:96:15)
    at WebViewImpl.dispatchEvent (electron/js2c/renderer_init.js:155:2221)
    at dispatchEvent (electron/js2c/renderer_init.js:143:1883)
    at electron/js2c/renderer_init.js:143:3008
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:127:872)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)
```

### Commands

```
     -0:02.2.0 intentions:highlight (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-browser 1.10.0 
atom-clock 0.1.18 
atom-html-preview 0.2.6 
atom-hugo 0.1.2 
atom-translator 0.3.0 
browser-plus 0.0.98 
busy-signal 2.0.1 
double-tag 1.7.0 
emmet 2.4.3 
font-viewer 1.0.5 
hey-pane 1.2.0 
intentions 1.1.5 
language-hugo 0.5.1 
language-markdown 0.37.0 
language-svg 0.9.2 
linter 3.3.1 
linter-htmlhint 1.6.3 
linter-sass-lint 1.9.0 
linter-spell 0.15.0 
linter-spell-html 0.7.0 
linter-ui-default 3.3.1 
minimap 4.39.14 
minimap-cursorline 1.0.4 
minimap-selection 4.5.4 
pdf-view 0.73.0 
pdf-view-plus 1.11.0 
pigments 0.40.6 
pinned-tabs 2.3.1 
platformio-ide-terminal 2.10.1 
split-diff 1.6.1 
svg-preview 0.14.0 
svgo 5.0.0 
termination 0.7.6 
```

**Comment by clecap** [comment]
Same problem here with

1.57.0 x64 Atom on Electron 9.4.4 and Chrome 83.0.4103.122.

**Comment by clecap** [comment]
And the same issue with ATOM nightly, version 1.59.0-nightly8

**Comment by plamen19** [comment]
Same issue here.

`TypeError: this.html.webview.getWebContents is not a function
    at AtomBrowserViewBrowser.zoomUpdate (/home/plamen/.atom/packages/atom-browser/lib/atom-browser-view-browser.js:283:29)
    at HTMLElement.<anonymous> (/home/plamen/.atom/packages/atom-browser/lib/atom-browser-view-browser.js:96:15)
    at WebViewImpl.dispatchEvent (electron/js2c/renderer_init.js:155:2221)
    at dispatchEvent (electron/js2c/renderer_init.js:143:1883)
    at electron/js2c/renderer_init.js:143:3008
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:127:872)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)`

**Comment by sean-codes** [comment]
Looking into this. It seems `getWebContents` was deprecated.

https://www.electronjs.org/docs/breaking-changes#removed-webviewgetwebcontents

**Comment by sean-codes** [comment]
Updated package to work with newer versions of atom. Thank you for reporting this issue ❤️
