### ISSUE TITLE
Failed to activate the atom-browser package

### ISSUE THREAD

**Issue by ColinAlanHB** [sean-codes/atom-browser#8]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-browser](https://github.com/sean-codes/atom-browser) package 0.55.4

### Stack Trace

Failed to activate the atom-browser package

```
At ENOENT: no such file or directory, open 'null/templates/webview.json'

Error: ENOENT: no such file or directory, open 'null/templates/webview.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at AtomGoogleView.loadTemplate (/packages/atom-browser/lib/atom-browser-view.js:85:36)
    at /packages/atom-browser/lib/atom-browser-view.js:24:25)
    at Object.activate (/app.asar/node_modules/atom-browser/lib/atom-browser.js:22:19)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:253:19)
    at /app.asar/src/package.js:225:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:97:15)
    at /app.asar/src/package.js:218:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:215:34)
    at PackageManager.activatePackage (/app.asar/src/package-manager.js:692:36)
    at config.transactAsync (/app.asar/src/package-manager.js:667:30)
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:365:18)
    at PackageManager.activatePackages (/app.asar/src/package-manager.js:665:17)
    at PackageManager.activate (/app.asar/src/package-manager.js:644:44)
    at loadStatePromise.loadState.then (/app.asar/src/atom-environment.js:788:21)
```

### Commands

```
     -0:14.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:09.5.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:05.0 atom-browser:preview (span.name.icon.html5-icon.medium-orange)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
emmet 2.4.3 
```

**Comment by sean-codes** [comment]
@ColinAlanHB Hi! Thanks for reporting! Can you please provide me the steps to reproduce this ❤️
